
import { Restaurant, Group } from './types';

export const AREAS = ['新竹市東區', '新竹市北區', '新竹市香山區', '竹北市'];

const BASE_RESTAURANTS: Restaurant[] = [
  {
    id: '1',
    name: 'Shabu Shabu Paradise',
    rating: 4.5,
    distanceKm: 1.2,
    avgCostMin: 400,
    avgCostMax: 600,
    avgWaitMin: 15,
    avgWaitMax: 20,
    mealTimeHours: 2,
    hours: '11:00-15:00, 17:00-23:00',
    address: '300新竹市東區三民路158號',
    phone: '03 535 8800',
    services: ['吃到飽', '只收現金', '需要預定', '30元開鍋費'],
    foodTypes: ['點餐制單人鍋', '沙拉吧吃到飽', '冰品供應'],
    seats: 44,
    area: '新竹市東區',
    isOpen: true,
    images: ['https://picsum.photos/800/600?random=1', 'https://picsum.photos/800/600?random=2'],
    description: 'Premium hotpot experience with unlimited salad bar.',
    lat: 24.8,
    lng: 120.9
  },
  {
    id: '2',
    name: 'Spicy Soul Noodles',
    rating: 4.8,
    distanceKm: 0.5,
    avgCostMin: 150,
    avgCostMax: 250,
    avgWaitMin: 30,
    avgWaitMax: 45,
    mealTimeHours: 1,
    hours: '11:00-21:00',
    address: '300新竹市北區長安街10號',
    phone: '03 522 1234',
    services: ['無預約', '現金交易'],
    foodTypes: ['牛肉麵', '滷味'],
    seats: 20,
    area: '新竹市北區',
    isOpen: true,
    images: ['https://picsum.photos/800/600?random=3', 'https://picsum.photos/800/600?random=4'],
    description: 'Authentic spicy beef noodles passed down for generations.',
    lat: 24.81,
    lng: 120.96
  },
  {
    id: '3',
    name: 'Ocean Fresh Seafood',
    rating: 4.2,
    distanceKm: 5.5,
    avgCostMin: 800,
    avgCostMax: 1200,
    avgWaitMin: 0,
    avgWaitMax: 10,
    mealTimeHours: 2.5,
    hours: '16:00-23:00',
    address: '300新竹市香山區海山港路1號',
    phone: '03 538 5678',
    services: ['刷卡', '包廂'],
    foodTypes: ['現撈海鮮', '台式熱炒'],
    seats: 100,
    area: '新竹市香山區',
    isOpen: false,
    images: ['https://picsum.photos/800/600?random=5', 'https://picsum.photos/800/600?random=6'],
    description: 'Fresh catch from the harbor daily.',
    lat: 24.78,
    lng: 120.91
  },
  {
    id: '4',
    name: 'Veggie Green House',
    rating: 4.6,
    distanceKm: 2.0,
    avgCostMin: 300,
    avgCostMax: 500,
    avgWaitMin: 10,
    avgWaitMax: 15,
    mealTimeHours: 1.5,
    hours: '10:00-20:00',
    address: '300新竹市東區光復路二段101號',
    phone: '03 571 1111',
    services: ['素食友善', '寵物友善'],
    foodTypes: ['義大利麵', '燉飯'],
    seats: 30,
    area: '新竹市東區',
    isOpen: true,
    images: ['https://picsum.photos/800/600?random=7'],
    description: 'Healthy vegetarian options for everyone.',
    lat: 24.80,
    lng: 120.99
  },
  {
    id: '4b',
    name: 'Zhubei Brunch Club',
    rating: 4.3,
    distanceKm: 2.8,
    avgCostMin: 280,
    avgCostMax: 480,
    avgWaitMin: 15,
    avgWaitMax: 25,
    mealTimeHours: 1.5,
    hours: '09:00-16:00',
    address: '302新竹縣竹北市文信路101號',
    phone: '03 558 7788',
    services: ['刷卡', '寵物友善'],
    foodTypes: ['早午餐', '咖啡'],
    seats: 45,
    area: '竹北市',
    isOpen: true,
    images: ['https://picsum.photos/800/600?random=71'],
    description: 'Popular brunch spot in Zhubei with pet-friendly patio.',
    lat: 24.83,
    lng: 121.01
  }
];

// Generate more mock data to support swiping functionality
export const MOCK_RESTAURANTS: Restaurant[] = [
  ...BASE_RESTAURANTS,
  {
    id: '5',
    name: 'Hsinchu Roast Duck',
    rating: 4.7,
    distanceKm: 3.2,
    avgCostMin: 600,
    avgCostMax: 900,
    avgWaitMin: 20,
    avgWaitMax: 40,
    mealTimeHours: 2,
    hours: '11:00-20:00',
    address: '300新竹市東區中華路二段',
    phone: '03 512 3344',
    services: ['預約制', '適合團體'],
    foodTypes: ['烤鴨', '港式點心'],
    seats: 80,
    area: '新竹市東區',
    isOpen: true,
    images: ['https://picsum.photos/800/600?random=8'],
    description: 'Famous roast duck.',
    lat: 24.82,
    lng: 121.0
  },
  {
    id: '6',
    name: 'Night Market Steak',
    rating: 4.0,
    distanceKm: 1.5,
    avgCostMin: 180,
    avgCostMax: 300,
    avgWaitMin: 15,
    avgWaitMax: 25,
    mealTimeHours: 1.5,
    hours: '17:00-01:00',
    address: '300新竹市北區城隍廟邊',
    phone: '0912 345 678',
    services: ['只收現金', '外帶'],
    foodTypes: ['牛排', '鐵板麵'],
    seats: 30,
    area: '新竹市北區',
    isOpen: false,
    images: ['https://picsum.photos/800/600?random=9'],
    description: 'Affordable and tasty steak.',
    lat: 24.81,
    lng: 120.95
  },
  {
    id: '7',
    name: 'Mountain View Cafe',
    rating: 4.4,
    distanceKm: 8.0,
    avgCostMin: 250,
    avgCostMax: 400,
    avgWaitMin: 5,
    avgWaitMax: 10,
    mealTimeHours: 3,
    hours: '10:00-18:00',
    address: '300新竹市香山區景觀大道',
    phone: '03 599 8877',
    services: ['景觀座位', '寵物友善', '素食友善'],
    foodTypes: ['咖啡', '鬆餅'],
    seats: 50,
    area: '新竹市香山區',
    isOpen: true,
    images: ['https://picsum.photos/800/600?random=10'],
    description: 'Relax with a view.',
    lat: 24.75,
    lng: 120.90
  },
  {
    id: '8',
    name: 'Traditional Hakka Food',
    rating: 4.3,
    distanceKm: 4.0,
    avgCostMin: 300,
    avgCostMax: 500,
    avgWaitMin: 0,
    avgWaitMax: 20,
    mealTimeHours: 2,
    hours: '11:00-14:00, 17:00-21:00',
    address: '300新竹市東區金山街',
    phone: '03 666 7788',
    services: ['圓桌', '合菜'],
    foodTypes: ['客家小炒', '薑絲大腸'],
    seats: 120,
    area: '新竹市東區',
    isOpen: true,
    images: ['https://picsum.photos/800/600?random=11'],
    description: 'Classic Hakka dishes.',
    lat: 24.79,
    lng: 121.02
  },
  {
    id: '9',
    name: 'Late Night Izakaya',
    rating: 4.9,
    distanceKm: 1.8,
    avgCostMin: 800,
    avgCostMax: 1500,
    avgWaitMin: 10,
    avgWaitMax: 30,
    mealTimeHours: 3,
    hours: '18:00-02:00',
    address: '300新竹市北區北大路',
    phone: '03 525 9900',
    services: ['酒類供應', '可預約'],
    foodTypes: ['串燒', '清酒'],
    seats: 25,
    area: '新竹市北區',
    isOpen: false,
    images: ['https://picsum.photos/800/600?random=12'],
    description: 'Perfect for late night drinks.',
    lat: 24.81,
    lng: 120.97
  },
  {
    id: '10',
    name: 'Sunny Brunch',
    rating: 4.5,
    distanceKm: 2.5,
    avgCostMin: 250,
    avgCostMax: 350,
    avgWaitMin: 20,
    avgWaitMax: 60,
    mealTimeHours: 1.5,
    hours: '08:00-16:00',
    address: '300新竹市東區關新路',
    phone: '03 577 6655',
    services: ['早午餐', '親子友善'],
    foodTypes: ['歐姆蛋', '班尼迪克蛋'],
    seats: 40,
    area: '新竹市東區',
    isOpen: true,
    images: ['https://picsum.photos/800/600?random=13'],
    description: 'Best brunch in town.',
    lat: 24.79,
    lng: 121.01
  }
];

export const MOCK_GROUPS: Group[] = [
  {
    id: 'g1',
    name: 'Friday Night Squad',
    note: 'Celebrate John\'s promotion',
    area: '新竹市東區',
    date: '10/25',
    time: '19:00',
    swipingAmount: 10,
    isVegetarian: false,
    members: [
      { id: 'user_john', name: 'John', isHost: true },
      { id: 'user_alice', name: 'Alice' },
      { id: 'user_bob', name: 'Bob' }
    ],
    inviteLink: 'https://where_to_eat.app/join/g1',
    idealPriceRange: '200-600',
    maxWaitTime: '15 min'
  }
];
